### PR TITLE
Use getFilesystemPathForStaticAsset() consistently, everywhere

### LINKED ISSUE #1266: Environment verification failed
**Describe the bug**
On startup Chrysalis warns me:

> Environment verification failed
> Chrysalis has detected that it is running in an unsupported environment, such as with an Electron version other than the one supported upstream. If you are using Chrysalis through a distribution's package repository, please consider using the official builds instead.

This persists after uninstalling and freshly downloading and installing [the official 0.13.0 release from yesterday](https://github.com/keyboardio/Chrysalis/releases/download/v0.13.0/Chrysalis-0.13.0-universal.dmg).

**To Reproduce**
1. Download [Chrysalis-0.13.0-universal.dmg](https://github.com/keyboardio/Chrysalis/releases/download/v0.13.0/Chrysalis-0.13.0-universal.dmg)
1. Open it
1. Drag the app to the Applications folder
1. Open the Applications folder
1. Find Chrysalis
1. Run it

**Expected behavior**
Either no warning, or that warning with specific information I can use to fix the problem rather than general advice I've already followed.

**Screenshots**
Environment verification failed: Chrysalis has detected that it is running in an unsupported environment…

<details><summary>Elided debug bundle</summary>

```json
{
  "timestamp": "2023-05-08T01:35:02.701Z",
  "uuid": "...",
  "chrysalis": {
    "version": "0.13.0"
  },
  "os": {
    "platform": "darwin",
    "distro": "macOS",
    "release": "(a)",
    "codename": "macOS",
    "kernel": "22.4.0",
    "arch": "x64",
    "hostname": "...",
    "fqdn": "...",
    "codepage": "UTF-8",
    "logofile": "darwin",
    "serial": "...",
    "build": "22E772610a",
    "servicepack": "",
    "uefi": true
  },
  "usb": [
    {
      "id": 22,
      "bus": null,
      "deviceId": null,
      "name": "Model 100",
      "type": "Storage",
      "removable": true,
      "vendor": "Keyboardio",
      "manufacturer": "Keyboardio",
      "maxPower": null,
      "serialNumber": "..."
    }
  ],
  "logs": []
}
```
</details>

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (a) (22E772610a)
 - Chrysalis Version: 0.13.0

**Additional context**
None known.

### PR DESCRIPTION
**Pull request by algernon**
Rather than using a hodge-podge mix of `getStaticPath()` and `getFilesystemPathForStaticAsset()` for the same purposes, just use the latter, everywhere. This allows us to make `getStaticPath()` private.

Furthermore, adjust both to actually return the correct path both in development, and in production mode. This fixes #1266.

### CODE REVIEW

File: src/renderer/config.js [hunk 1]
```diff
@@ -25,22 +25,18 @@ function getStaticPath() {
...
   } else {
-    return path.join(__dirname, "..", "..", "..", "..", "static");
+    return path.join("..", "..", "..", "..", "static");
   }
 }
 
 function getFilesystemPathForStaticAsset(asset) {
   if (isDevelopment) {
-    return path.join(
-      ipcRenderer.sendSync("file.get-application-root"),
```
Comment (obra) [inline src/renderer/config.js:37]: I have some recollection that __dirname doesn't work in the renderer in production mode any more. is there any hint from the commit message about why I did that?

But if we don't need the rpc, great -- and we should remove the api on the server-side process as well

**Comment by obra** [comment]
approved.
