### PR TITLE
FirmwareUpdate: Rework how we do factory resets

### LINKED ISSUE #1112: Factory Reset is a lie when connecting in bootloader mode
**Describe the bug**
One workaround for poor communications with Chrysalis and the factory Model 100 firmware is to force bootloader mode before connecting in Chrysalis. Unfortunately, if you then select the Factory Reset option when prompted to upgrade the firmware, the EEPROM does not get erased, despite the UI feedback implying that it will.

**To Reproduce**
1. Start Chrysalis without the keyboard connected.
2. Plug in a Model 100 keyboard while holding down PROG, to force bootloader mode.
3. Connect to the keyboard in Chrysalis.
4. Click Upgrade Firmware when prompted.
5. Select Factory Reset, and click the prompts to continue.
6. Observe that flashing completes, but only performs a "flashing" step.
7. Reconnect to the keyboard in Chrysalis.
8. Observe that any previous custom keymap layout settings remain intact.

**Expected behavior**
"Factory Reset" should behave as advertised, even when using the "connect to Chrysalis while in bootloader mode" workaround for poor connectivity with factory firmware.

**Screenshots**
N/A; there are lots of steps involved, and the description is hopefully clear enough to replicate the failure.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7 (19H2026)
 - Chrysalis Version: 0.11.5, but also 0.11.4 and maybe earlier as well.
 
**Additional context**
I came across this while trying to provide more robust steps for reflashing from Model 100 factory firmware in #1108.

### PR DESCRIPTION
**Pull request by algernon**
The major part of this pull request is a rework of how we do factory resets. Originally we were erasing the EEPROM *before* going into bootloader mode, because that was easy to do. Unfortunately, it is also the wrong thing to do, because that prevents us from performing the same feat when starting from bootloader mode. We really want to do the erase after flashing new firmware, and before restoring the previous settings.

This pull request achieves that, and does a bit more under the hood, because those changes were necessary to be able to rearrange the order of flash steps. These changes include:

- The rearrangement fixes #1112.
- Lifting out `flashSteps()` from the hardware descriptors, and making Chrysalis use the same logic for every keyboard. (This addresses some of #1015)
- We no longer need `Model100Bootloader`, so that was removed as well. (This addresses another part of #1015)
- We're catching and handling a few edge cases we weren't handling properly before. These cases happen more often with the new flow, while they were pretty rare previously. And now we handle them correctly.

There are still improvements (lifting the flashing steps into their own functions, and actually turning it into a real state machine) that could be made in this area of Chrysalis, but those - I feel - are out of scope for this PR, and I will deal with them in a followup.

### CODE REVIEW

File: src/api/flash.js [hunk 1]
```diff
@@ -47,6 +47,7 @@ export const RebootMessage = {
 export const flash = async (flasher, board, port, filename, options) => {
   const focusCommands = new FocusCommands(options);
   const device = options.device;
+  const startFromBoot = device.bootloader;
```
Comment (obra) [inline src/api/flash.js:50]: let's actually spell it out as Bootloader instead of Boot

File: src/api/flash.js [hunk 2]
```diff
@@ -154,34 +144,64 @@ export const flash = async (flasher, board, port, filename, options) => {
...
-        onError(RebootMessage.reconnect.stillBootloader);
-      } else {
-        onError(RebootMessage.reconnect.notFound);
+        flasher.rebootToNormal(bootloaderFound, options.device);
       }
-    }
 
-    if (bootloaderFound) {
-      flasher.rebootToNormal(bootloaderFound, options.device);
+      await delay(2000);
```
Comment (obra) [inline src/api/flash.js:171]: Add a comment explaining what we're waiting for?

File: src/api/flash.js [hunk 3]
```diff
@@ -59,80 +60,67 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+     * - Check for the bootloader every 2s
+     * - If found, we're done
+     * - If not found, try again
+     * - If not found for N attempts, show a notification
+     ***/
+    await toStep(callback)("bootloader");
+    let bootloaderFound = false;
+    let attempts = 0;
+    while (!bootloaderFound) {
+      const normalDevice = await options.focus.checkSerialDevice(
```
Comment (obra) [inline src/api/flash.js:89]: maybe something like deviceInApplicationMode or something?

File: src/api/flash.js [hunk 4]
```diff
@@ -59,80 +60,67 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+        options.device,
+        options.device.usb
+      );
+
+      try {
+        await focusCommands.reboot(normalDevice, options.device);
```
Comment (obra) [inline src/api/flash.js:95]: instead of just passing options.device through, explicitly enumerate the device options we're using.

File: src/api/flash.js [hunk 5]
```diff
@@ -59,80 +60,67 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+    await toStep(callback)("bootloader");
+    let bootloaderFound = false;
+    let attempts = 0;
+    while (!bootloaderFound) {
+      const normalDevice = await options.focus.checkSerialDevice(
+        options.device,
+        options.device.usb
+      );
+
+      try {
```
Comment (obra) [inline src/api/flash.js:94]: This feels like it should get pulled out into a reboot function.

File: src/api/flash.js [hunk 6]
```diff
@@ -59,80 +60,67 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+        // ignore any errors here
       }
-    }
+      await delay(2000);
 
-    try {
-      await focusCommands.reboot(normalDevice, options.device);
-    } catch (_) {
-      // ignore any errors here
+      bootloaderFound = await options.focus.checkBootloader(options.device);
```
Comment (obra) [inline src/api/flash.js:101]: Pull this out into a function and lift stuff out of "options"

File: src/api/flash.js [hunk 7]
```diff
@@ -154,34 +144,64 @@ export const flash = async (flasher, board, port, filename, options) => {
...
 
   /***
-   * When the keyboard is back up, restore the structured EEPROM save.
+   * When the keyboard is back up:
+   * - clear the eeprom
+   * - reconnect again
+   * - restore the structured EEPROM save.
    ***/
-  await toStep(callback)("restoreEEPROM");
+  if (options.factoryReset) {
```
Comment (obra) [inline src/api/flash.js:184]: We could make this clearer by always sending the "clearing eeprom" message.

File: src/api/flash.js [hunk 8]
```diff
@@ -59,80 +60,67 @@ export const flash = async (flasher, board, port, filename, options) => {
...
-    if (e != "Communication timeout") {
-      throw new Error(e);
+  if (!startFromBoot) {
+    /***
+     * Preparations before flashing:
+     * - If not doing a factory reset, save a structured eeprom backup.
+     * - Otherwise proceed.
+     ***/
+    if (!options.factoryReset) {
+      await toStep(callback)("saveEEPROM");
```
Comment (obra) [inline src/api/flash.js:73]: The whole 'toStep' thing would be clearer if we called it something like 'reportUpdateStatus'

File: src/api/flash.js [hunk 9]
```diff
@@ -154,34 +144,64 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+          onError(RebootMessage.reconnect.notFound);
+        }
+      }
 
-    if (attempts == NOTIFY_THRESHOLD) {
       if (bootloaderFound) {
-        onError(RebootMessage.reconnect.stillBootloader);
-      } else {
-        onError(RebootMessage.reconnect.notFound);
+        flasher.rebootToNormal(bootloaderFound, options.device);
```
Comment (obra) [inline src/api/flash.js:168]: ApplicationMode instead of 'Normal'?

File: src/api/flash/FocusCommands.js [hunk 10]
```diff
@@ -30,6 +30,14 @@ export function FocusCommands(options) {
     let port = focus._port;
 
     if (devicePort && focusDeviceDescriptor) {
+      if (port?.isOpen) {
```
Comment (obra) [inline src/api/flash/FocusCommands.js:33]: Since we repeat this pattern multiple times, maybe we should move it into focus?

File: src/api/flash/FocusCommands.js [hunk 11]
```diff
@@ -30,6 +30,14 @@ export function FocusCommands(options) {
     let port = focus._port;
```
Comment (obra) [inline src/api/flash/FocusCommands.js:30]: Not for this PR, but we access focus._port all over the place, even though it's nominally "private" - In most code, I bet we should have an accessor in ActiveDevice

File: src/api/hardware/index.js [hunk 12]
```diff
@@ -16,17 +16,13 @@
...
-  Model100Bootloader,
-} from "@api/hardware-keyboardio-model01";
+import { Model01, Model100 } from "@api/hardware-keyboardio-model01";
 import { Splitography } from "@api/hardware-softhruf-splitography";
 import { Atreus } from "@api/hardware-technomancy-atreus";
 
 const Hardware = {
   serial: [Model01, Model100, Atreus2, ErgoDox, Atreus, Splitography],
-  nonSerial: [Model100Bootloader, ErgoDox, Atreus, Splitography],
+  nonSerial: [Model100, ErgoDox, Atreus, Splitography],
```
Comment (obra) [inline src/api/hardware/index.js:25]: Is the Model100 really both `serial` and `nonSerial` - That's confusing to me. Can you add some comments explaining what the two different arrays do?

File: src/renderer/screens/FirmwareUpdate.js [hunk 13]
```diff
@@ -118,7 +117,22 @@ const FirmwareUpdate = (props) => {
   };
 
   const upload = async (options) => {
-    setFlashSteps(focusDeviceDescriptor.flashSteps(options));
+    let steps = [
```
Comment (obra) [inline src/renderer/screens/FirmwareUpdate.js:120]: I'm thrilled that this code is no longer per-device, but the current implementation is.....hard to read.

Instead of having nested ifs and concatenation, I'd rather see a simpler if {} else if {} else if {}  else {}  structure.

File: src/renderer/screens/FirmwareUpdate/FlashSteps.js [hunk 14]
```diff
@@ -25,7 +25,7 @@ import { useTranslation } from "react-i18next";
 const FlashSteps = (props) => {
   const { t } = useTranslation();
 
-  if (props.activeStep < 0) return null;
+  if (props.activeStep < 0 && props.steps.length > 1) return null;
```
Comment (obra) [inline src/renderer/screens/FirmwareUpdate/FlashSteps.js:28]: Add a comment explaining the logic?

File: src/api/flash/FocusCommands.js [hunk 15]
```diff
@@ -30,6 +30,14 @@ export function FocusCommands(options) {
...
 
     if (devicePort && focusDeviceDescriptor) {
+      if (port?.isOpen) {
+        try {
+          await port.close();
+        } catch (_) {
+          /* ignore the error */
+        }
+      }
+      focus._port = undefined;
```
Comment (obra) [inline src/api/flash/FocusCommands.js:40]: I think this line just convinced me that we want an acccessor / mutator on focus for the port variable.

File: src/api/flash.js [hunk 16]
```diff
@@ -154,34 +144,64 @@ export const flash = async (flasher, board, port, filename, options) => {
...
-  let kb = false;
-  attempts = 0;
-  while (!kb) {
-    kb = await options.focus.reconnectToKeyboard(device);
-    if (kb) break;
-    attempts += 1;
-
-    const bootloaderFound = await options.focus.checkBootloader(options.device);
+  const doReconnect = async () => {
+    let kb = false;
```
Comment (obra) [inline src/api/flash.js:148]: is `kb` `device_detected`?

File: src/api/flash.js [hunk 17]
```diff
@@ -154,34 +144,64 @@ export const flash = async (flasher, board, port, filename, options) => {
...
+    while (!kb) {
+      kb = await options.focus.reconnectToKeyboard(device);
+      if (kb) break;
+      attempts += 1;
+
+      const bootloaderFound = await options.focus.checkBootloader(
+        options.device
+      );
+
+      if (attempts == NOTIFY_THRESHOLD) {
```
Comment (obra) [inline src/api/flash.js:159]: tiny, but `NOTIFICATION_` instead of `NOTIFY_`

**Comment by obra** [comment]
Generally, yay! I left rather a lot of code feedback. One thing I'm seeing that I'd like us to adjust is language like "Normal" , "Device" and "Boot"  I think the things are called `BootloaderMode` and `ApplicationMode`.

File: src/api/flash.js (hunk 7 above)
Comment (obra) [reply src/api/flash.js:184]: What happens if we report a state that's not in the stepper?

**Comment by obra** [comment]
I'm ok with the non-trivial refactoring in a new PR, but would love to have you confirm functionality on the Model 01 and Atreus before we merge.
