### PR TITLE
Flash process overhaul

### LINKED ISSUE #941: Ideas to improve the flashing process
There are a few shortcomings in our current flashing process, one of which is the part where we wait for the keyboard to come back after successful flashing. In general, waiting for the device to come back one way or the other, is a bit fragile. However, the waiting for the bootloader step is easier in practice, because the bootloader triggering key can be pressed way before we get to the stage where we reboot.

On the other hand, after flashing, waiting for the keyboard to boot into the new firmware is more problematic. When the firmware is small, and the flashing is fast, it's possible to have a fairly short (3-7 sec) window to release the trigger key, and that's too short. If it isn't released during that window, the keyboard will remain in bootloader, and we'll never try to get it out of that again, and will ultimately fail the flashing process.

What we should do instead, is look for the bootloader too, and if we found the bootloader, warn the user to release the trigger key, and then reboot the keyboard and wait until we have it booted up, or we time out again. This gives the user another ~20 seconds to release the key.

On top of this, if we still fail the process, we should present a more useful error message, based on the step we failed at. This way if we fail at the reconnect step, we can tell the user that, and offer hints (like releasing the trigger key earlier).

### PR DESCRIPTION
**Pull request by algernon**
Our old flashing process suffered from a few shortcomings, biggest of which was its reliance on timing, and retries being woefully incomplete. In practice, this meant that if the key to help trigger bootloader mode was not pressed soon enough, or was released too late, we ended up in a state Chrysalis could not recover from, because it never tried the reset again.

The new process does away with the separate "bootloaderTrigger" and "bootloaderWait" steps, and combines them into a single "bootloader" step, which will take care of retrying the reboot too, whether from normal mode to bootloader, or the other way around. This also moves the retry logic into the flasher, out of `@api/focus`.

With the logic in the flasher, it can properly notify the renderer when the keyboard is in an unexpected state, and the renderer can - and with this patch, does - display an appropriate message the user can act on.

With retries in place, the flashing process should be more robust, and more forgiving, and far less reliant on timing.

Fixes #941, and likely a whole lot of other, flashing related issues.

On top of that, the process now also clear the EEPROM before flashing, so restore happens onto a fresh state (see #934 for an example where this is needed).

## TODO before this can get out of draft state:

- [x] Make sure flashing works when the keyboard is already in bootloader mode
- [x] Make sure the "factory reset" option works
- [x] Use `eeprom.erase` to clear the EEPROM during the procedure, rather than the `eeprom.contents 255...` fallback
- [x] Test all supported flashers on all three of the major operating systems:
  - [x] Linux
    - [x] AVRGirl
    - [x] DFUUtil
    - [x] DFUProgrammer
    - [x] Teensy
  - [x] macOS
    - [x] AVRGirl
    - [x] DFUUtil
    - [x] DFUProgrammer
    - [x] Teensy
  - [x] Windows
    - [x] AVRGirl
    - [x] DFUUtil
    - [x] ~~DFUProgrammer~~
    - [x] ~~Teensy~~
 - [x] Reduce the amount of logging on macOS: we do not want deep `serialport` debug logs neither on the console, nor in the logfiles
 - [x] Remove leftover `console.log()`s
 - [x] Rebase the branch of then-current master, and rearrange the commits to make sense

### CODE REVIEW

**Comment by algernon** [comment]
Couple of observations from some testing @obra made today:

- Atreus flashing works fine on macOS (and my testing shows it working on Linux too). Model01 uses the same bootloader, so that should be fine too.
- Model100 doesn't work at all on macOS, it times out. Works on Linux, though.
- macOS has a *ton* of verbose messages (27k+ in a single session, while on my Linux, 1k is already suspiciously high)
- flashing from bootloader is broken, both on this branch, and on master too
- the extra verbose logging is present on the Atreus too
- extra logs seem to be coming from `serialport`

**Comment by algernon** [comment]
Fixed the flashing from bootloader issue, both here, and on master. Factory reset is still broken on master, but works here.

I'll add a TODO list to the top, so we can keep track of what needs to be done to get this out of draft state.

**Comment by algernon** [comment]
Turns out the macOS logging wasn't specific to macOS. It's the `debug` npm package doing its... "thing". If the `DEBUG` env var is set, the package will cache it in `localStorage`, and will continue using the cached value until manually cleared. Setting a different `DEBUG` value will **not** override what is in `localStorage`.

So what happened is that at some point in the past `DEBUG` was likely set to `*` or `serialport:*` or something along those lines, perhaps not even for Chrysalis, but another Electron app in dev mode (since they'd share local storage), it was cached in local storage, and ended up spamming the Chrysalis console.

The solution is doing a `localStorage.debug=""` using the dev console, and restarting Chrysalis to make sure its working.

**Comment by algernon** [comment]
Verified that the Model100 flashing on macOS was broken by excessive logging. With `DEBUG=*`, flashing fails. Clearing it out from localStorage, and the same process worked 10 times in a row without a hitch.

**Comment by algernon** [comment]
Okay, current state: I managed to make everything else work, but broke Model100 flashing in the process. It's all due to how we detect bootloaders and devices. It turns out, that is another very fragile area, which I will need to rework before I can continue.

**Comment by algernon** [comment]
Model100 unborked

**Comment by algernon** [comment]
I tried DFUUtil (Model100) with a Windows VM, and it worked flawlessly.

I tried AVRGirl (Keyboardio Atreus), that also worked, but there were access denied errors on the console after flashing was done, while trying to reconnect. The keyboard was still in bootloader mode at the time. Once it settled back to normal mode, and I redirected it to the VM again, the flashing process finished. This could use some testing on a real windows.

**Comment by obra** [comment]
If this tests correctly on Windows, I'm +1 to merge

**Comment by algernon** [comment]
I'm a bit worried about the AVRGirl flasher on Windows. Those permission denied things in the VM weren't encouraging. I think I'll hunt those down, and then I'll see about finding a win10/11 thing to test on that isn't a VM. Or perhaps VM works, if I use VirtualBox where I can auto-redirect devices, and can test the whole procedure without linux interfering.

**Comment by algernon** [comment]
@obra tested flashing an Atreus and a Model 100 on Windows, and those worked too, so we got the Windows parts covered too!

After those good news, I rebased the branch on top of master, and cleaned up its history. This is now ready.

File: src/api/flash/AVRGirlFlasher.js [hunk 1]
```diff
@@ -15,90 +15,28 @@
...
+  logger("flash").debug("rebooting to normal mode");
   try {
-    await port.close();
-  } catch (_) {
-    /* ignore the error */
+    const serial = new SerialPort({
+      path: port.path,
+      baudRate: 9600,
+    });
+    serial.write("E");
```
Comment (obra) [inline src/api/flash/AVRGirlFlasher.js:30]: Can this get documented with comments, possibly even comments pointing to a spec?

File: src/api/flash/AVRGirlFlasher.js [hunk 2]
```diff
@@ -15,90 +15,28 @@
...
+  } catch (e) {
+    logger("flash").error("error while trying to reboot to normal mode", {
```
Comment (obra) [inline src/api/flash/AVRGirlFlasher.js:32]: Do errors not get localized?

File: src/api/flash/DFUProgrammerFlasher.js [hunk 3]
```diff
@@ -21,7 +21,47 @@ import path from "path";
...
 import { delay, toStep } from "./utils";
 
-export const DFUProgrammerFlasher = async (board, port, filename, options) => {
+const rebootToNormal = async (port, _) => {
+  logger("flash").debug("rebooting to normal mode");
+  await runDFUProgrammer(["atmega32u4", "start"]);
+};
+
+const runDFUProgrammer = async (args) => {
+  const timeout = 1000 * 60 * 5;
```
Comment (obra) [inline src/api/flash/DFUProgrammerFlasher.js:30]: It's obvious that it's a timeout, can we name it to describe *what* is timing out?

File: src/api/flash/AVRGirlFlasher.js (hunk 2 above)
Comment (algernon) [reply src/api/flash/AVRGirlFlasher.js:32]: This isn't shown to the user, it's just for the internal logs, and those aren't localized. In general, `logger(...).whatever(...)` is for internal use only, and isn't shown in-app.

File: src/api/flash/DFUUtilFlasher.js [hunk 4]
```diff
@@ -21,70 +21,68 @@ import path from "path";
...
-          logger("flash").debug("dfu-util done");
-          resolve();
-        } else {
-          logger("flash").error("dfu-util exited abnormally", {
-            exitCode: code,
-          });
-          reject("dfu-util exited abnormally with an error code of " + code);
-        }
-      });
+  const timeout = 1000 * 60 * 5;
```
Comment (obra) [inline src/api/flash/DFUUtilFlasher.js:32]: and the same timeout again. maybe we should lift this?

File: src/api/flash/DFUUtilFlasher.js [hunk 5]
```diff
@@ -21,70 +21,68 @@ import path from "path";
...
+          exitCode: code,
+        });
+        reject("dfu-util exited abnormally with an error code of " + code);
+      }
     });
-  };
+  });
+};
+
+const formatID = (desc) => {
```
Comment (obra) [inline src/api/flash/DFUUtilFlasher.js:62]: is that a USB Id? can we name it to be more descriptive? also, since other things are Id, calling this ID feels wrong.

File: src/api/flash/TeensyFlasher.js [hunk 6]
```diff
@@ -20,13 +20,23 @@ import TeensyLoader from "teensy-loader";
 
 import { delay, toStep } from "./utils";
 
-export const TeensyFlasher = async (board, port, filename, options) => {
+const rebootToNormal = async (port) => {
+  logger("flash").debug("rebooting to normal mode");
+  const device = await TeensyLoader.open(0x16c0, 0x0478);
```
Comment (obra) [inline src/api/flash/TeensyFlasher.js:25]: what are those constants? let's name em.

File: src/api/focus.js [hunk 7]
```diff
@@ -111,114 +111,112 @@ class Focus {
...
-    return false;
+
+    return null;
   }
 
-  async waitForBootloader(focusDeviceDescriptor) {
+  async checkBootloader(focusDeviceDescriptor) {
     if (!focusDeviceDescriptor.usb.bootloader) {
-      this.logger.warn("No bootloader defined in the device descriptor", {
+      this.logger().warn("No bootloader defined in the device descriptor", {
```
Comment (obra) [inline src/api/focus.js:189]: What's the difference between this.logger().warn and  logger("focus").info other than log level? we use both in this function

File: src/api/focus.js [hunk 8]
```diff
@@ -111,114 +111,112 @@ class Focus {
...
+      return false;
     }
-    logger("focus").info("waiting for bootloader", {
+    logger("focus").info("checking bootloader presence", {
       descriptor: focusDeviceDescriptor,
     });
 
-    if (focusDeviceDescriptor.usb.bootloader.type == "dfu") {
-      return await this.waitForDFUBootloader(focusDeviceDescriptor);
+    if (focusDeviceDescriptor.usb.bootloader.type == "non-serial") {
```
Comment (obra) [inline src/api/focus.js:198]: maybe it should just be !== "serial" rather than having a constant that's "not serial"?

File: src/api/focus.js [hunk 9]
```diff
@@ -111,114 +111,112 @@ class Focus {
...
   async reconnectToKeyboard(focusDeviceDescriptor) {
     logger("focus").info("reconnecting to keyboard", {
       descriptor: focusDeviceDescriptor,
     });
-    const d = await this.waitForSerialDevice(
+    const d = await this.checkSerialDevice(
       focusDeviceDescriptor,
       focusDeviceDescriptor.usb
     );
+    if (!d) return false;
```
Comment (obra) [inline src/api/focus.js:213]: what is "d" here? is it "device connected"? is it "device available"? can you use a longer name?

File: src/renderer/screens/FirmwareUpdate/FlashNotification.js [hunk 10]
```diff
@@ -0,0 +1,97 @@
...
+    );
+  } else if (props.message == RebootMessage.reconnect.stillBootloader) {
+    contents = (
+      <>
+        <Typography component="p" sx={{ mb: 2 }}>
+          {t("firmwareUpdate.flashing.notifications.reconnect.stillBootloader")}
+        </Typography>
+      </>
+    );
+  } else if (props.message == RebootMessage.reconnect.notFound) {
```
Comment (obra) [inline src/renderer/screens/FirmwareUpdate/FlashNotification.js:69]: does js not want us to use === here?

File: src/api/flash/TeensyFlasher.js (hunk 6 above)
Comment (algernon) [reply src/api/flash/TeensyFlasher.js:25]: that's the HalfKay bootloader vendor/prod ids, and yes we can name them.

File: src/api/focus.js (hunk 8 above)
Comment (algernon) [reply src/api/focus.js:198]: Can do. Should I lift it out into a constant, too, or are we ok with a string for now?

(note: this part of the code I will be reworking next, so this whole bootloader type thing may either be completely gone, or look very different in a week)

**Comment by obra** [comment]
we could even pull them from the device boot loader info right?

File: src/api/flash/DFUUtilFlasher.js (hunk 4 above)
Comment (algernon) [reply src/api/flash/DFUUtilFlasher.js:32]: As discussed on discord: we could, and should, but this is something I'll do separately, because there's more to lift out here than the timeout alone, and that's something independent of this PR. I'll name both of them better, but will do the lifting in an upcoming PR.

File: src/api/focus.js (hunk 7 above)
Comment (algernon) [reply src/api/focus.js:189]: The difference is that `logger()` exists, and `this.logger()` does not. =)

**Comment by algernon** [comment]
Review notes addressed, new version force pushed.

**Comment by obra** [comment]
+1 to merge. go for it.
